os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
        env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
language: c++
compiler: g++
before_install: 
    - sudo apt-get update
    - git clone https://github.com/google/googletest.git
    - ls
    - eval "${MATRIX_EVAL}"
script: mkdir build && cd build && cmake .. && make
