os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
        env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
language: c++
compiler: g++
before_install: 
    - sudo apt-get update
    - sudo apt-get install -y libgtest-dev
    - git clone https://github.com/google/googletest.git && cd googletest
    - mkdir build && cd build
    - cmake .. && sudo make install
    - cd ../..
    - eval "${MATRIX_EVAL}"
script: mkdir build && cd build && cmake .. && make
